ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.vitalir.kotlinvcshub.server.ApplicationKt.mainModule
jwt:
  secret: "secret" #TODO maybe replace by HOCON for default vals?
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to hello"
