services:
  server:
    build: .
    container_name: kotlinvcshub-server
    ports:
      - 8080:8080
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:?No username for db connection was set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?No password for db connection was set}
      POSTGRES_DATABASE_NAME: ${POSTGRES_DB:?No db name was set}
      POSTGRES_SERVER_NAME: ${POSTGRES_SERVER_NAME:?No server name for db was set}
      JWT_SECRET: ${JWT_SECRET:?No jwt secret was set}
      JWT_REALM: ${JWT_REALM:?No jwt realm was set}
      IS_DEVELOPMENT: ${IS_DEVELOPMENT}
    depends_on:
      db-main:
        condition: service_healthy
  db-main:
    image: postgres:15.0-alpine
    container_name: kotlinvcshub-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?No password for db-main was set}
      POSTGRES_DB: ${POSTGRES_DB:?No db name for db-main was set}
    ports:
      - 54332:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
