services:
  server:
    build: .
    container_name: kotlinvcshub-server
    ports:
      - 8080:8080
    depends_on:
      db-main:
        condition: service_healthy
  db-main:
    image: postgres:15.0-alpine
    container_name: kotlinvcshub-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?No password for db-main was set}
      POSTGRES_DB: ${POSTGRES_DB:?No db name for db-main was set}
    ports:
      - 54332:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
