ktor:
  development: $IS_DEVELOPMENT
  deployment:
    port: 8080
  application:
    modules:
      - io.vitalir.kotlinhub.server.app.ApplicationKt.mainModule

jwt:
  secret: $JWT_SECRET
  issuer: "http://localhost/"
  audience: "http://localhost/"
  realm: $JWT_REALM

database:
  username: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  databaseName: $POSTGRES_DATABASE_NAME
  serverName: $POSTGRES_SERVER_NAME

repository:
  baseRepositoriesPath: $BASE_REPOSITORIES_PATH

debug:
  routeTracing: $ROUTE_TRACING
  docs: $DOCS

defaultAdmin:
  username: $DEFAULT_ADMIN_USERNAME
  password: $DEFAULT_ADMIN_PASSWORD
