ktor:
  development: $IS_DEVELOPMENT
  deployment:
    port: 8080
  application:
    modules:
      - io.vitalir.kotlinhub.server.app.ApplicationKt.mainModule

jwt:
  secret: $JWT_SECRET
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: $JWT_REALM

database:
  username: $POSTGRES_USERNAME
  password: $POSTGRES_PASSWORD
  databaseName: $POSTGRES_DATABASE_NAME
  serverName: $POSTGRES_SERVER_NAME

debug:
  routeTracing: $ROUTE_TRACING
